name: jsmalo
favicon: null
layout_spectrum: 0.51587
typography_spectrum: 0.54941
title: MULTIMEDIA GRAPHIC DESIGNER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2fc'
    - '#c37e57'
    - '#642307'
    - '#af496d'
    - '#e3002f'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
